version: 2
jobs:
  build:
    working_directory: ~/stackl
    docker:
      - image: jetcipher/circleci-dotnet-core:3.0
    steps:
      - checkout:
          path: ~/stackl
      - setup_remote_docker:
            docker_layer_caching: false
      - run:
          name: Build and push Docker image
          command: |
            docker build -t stackluser/backend .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push stackluser/backend
          working_directory: ~/stackl/StacklService